title = "Epimetheus Revolution"
baseURL = "https://lordofwill.github.io/"
languageCode = "kr"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "kr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = false

[languages]
  [languages.en]
    title = "Epimetheus Revolution"
    weight = 2
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.kr]
    title = "에피메테우스 혁명"
    weight = 1
    contentDir = "content/kr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/lordofwill"
